// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBCommon.proto

#ifndef PROTOBUF_PBCommon_2eproto__INCLUDED
#define PROTOBUF_PBCommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace PBCommon {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_PBCommon_2eproto();
void protobuf_AssignDesc_PBCommon_2eproto();
void protobuf_ShutdownFile_PBCommon_2eproto();


enum CSID {
  TCP_LOGIN = 1,
  TCP_REQUEST_MATCH = 10,
  TCP_CANCEL_MATCH = 11,
  UDP_BATTLE_READY = 51,
  UDP_UP_PLAYER_OPERATIONS = 53,
  UDP_UP_DELTA_FRAMES = 55,
  UDP_UP_GAME_OVER = 57
};
bool CSID_IsValid(int value);
const CSID CSID_MIN = TCP_LOGIN;
const CSID CSID_MAX = UDP_UP_GAME_OVER;
const int CSID_ARRAYSIZE = CSID_MAX + 1;

enum SCID {
  TCP_RESPONSE_LOGIN = 1,
  TCP_RESPONSE_REQUEST_MATCH = 10,
  TCP_RESPONSE_CANCEL_MATCH = 11,
  TCP_ENTER_BATTLE = 50,
  UDP_BATTLE_START = 51,
  UDP_DOWN_FRAME_OPERATIONS = 53,
  UDP_DOWN_DELTA_FRAMES = 55,
  UDP_DOWN_GAME_OVER = 57
};
bool SCID_IsValid(int value);
const SCID SCID_MIN = TCP_RESPONSE_LOGIN;
const SCID SCID_MAX = UDP_DOWN_GAME_OVER;
const int SCID_ARRAYSIZE = SCID_MAX + 1;

enum TeamType {
  NO = 0,
  TEAM1 = 1,
  TEAM2 = 2,
  TEAM3 = 3,
  TEAM4 = 4
};
bool TeamType_IsValid(int value);
const TeamType TeamType_MIN = NO;
const TeamType TeamType_MAX = TEAM4;
const int TeamType_ARRAYSIZE = TeamType_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace PBCommon

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PBCommon_2eproto__INCLUDED
