// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PBBattle.proto

/*
Package PBBattle is a generated protocol buffer package.

It is generated from these files:
	PBBattle.proto

It has these top-level messages:
	BattleUserInfo
	TcpEnterBattle
	UdpBattleReady
	UdpBattleStart
	PlayerOperation
	UdpUpPlayerOperations
	AllPlayerOperation
	UdpDownFrameOperations
	UdpUpDeltaFrames
	UdpDownDeltaFrames
	UdpUpGameOver
	UdpDownGameOver
*/
package PBBattle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RightOpType int32

const (
	RightOpType_noop   RightOpType = 0
	RightOpType_attack RightOpType = 1
)

var RightOpType_name = map[int32]string{
	0: "noop",
	1: "attack",
}
var RightOpType_value = map[string]int32{
	"noop":   0,
	"attack": 1,
}

func (x RightOpType) Enum() *RightOpType {
	p := new(RightOpType)
	*p = x
	return p
}
func (x RightOpType) String() string {
	return proto.EnumName(RightOpType_name, int32(x))
}
func (x *RightOpType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RightOpType_value, data, "RightOpType")
	if err != nil {
		return err
	}
	*x = RightOpType(value)
	return nil
}
func (RightOpType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BattleUserInfo struct {
	Uid              *int32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	BattleID         *int32 `protobuf:"varint,2,req,name=battleID" json:"battleID,omitempty"`
	RoleID           *int32 `protobuf:"varint,3,req,name=roleID" json:"roleID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BattleUserInfo) Reset()                    { *m = BattleUserInfo{} }
func (m *BattleUserInfo) String() string            { return proto.CompactTextString(m) }
func (*BattleUserInfo) ProtoMessage()               {}
func (*BattleUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BattleUserInfo) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *BattleUserInfo) GetBattleID() int32 {
	if m != nil && m.BattleID != nil {
		return *m.BattleID
	}
	return 0
}

func (m *BattleUserInfo) GetRoleID() int32 {
	if m != nil && m.RoleID != nil {
		return *m.RoleID
	}
	return 0
}

type TcpEnterBattle struct {
	RandSeed         *int32            `protobuf:"varint,1,req,name=randSeed" json:"randSeed,omitempty"`
	BattleUserInfo   []*BattleUserInfo `protobuf:"bytes,2,rep,name=battleUserInfo" json:"battleUserInfo,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *TcpEnterBattle) Reset()                    { *m = TcpEnterBattle{} }
func (m *TcpEnterBattle) String() string            { return proto.CompactTextString(m) }
func (*TcpEnterBattle) ProtoMessage()               {}
func (*TcpEnterBattle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TcpEnterBattle) GetRandSeed() int32 {
	if m != nil && m.RandSeed != nil {
		return *m.RandSeed
	}
	return 0
}

func (m *TcpEnterBattle) GetBattleUserInfo() []*BattleUserInfo {
	if m != nil {
		return m.BattleUserInfo
	}
	return nil
}

type UdpBattleReady struct {
	Uid              *int32 `protobuf:"varint,1,req,name=uid" json:"uid,omitempty"`
	BattleID         *int32 `protobuf:"varint,2,req,name=battleID" json:"battleID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UdpBattleReady) Reset()                    { *m = UdpBattleReady{} }
func (m *UdpBattleReady) String() string            { return proto.CompactTextString(m) }
func (*UdpBattleReady) ProtoMessage()               {}
func (*UdpBattleReady) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UdpBattleReady) GetUid() int32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *UdpBattleReady) GetBattleID() int32 {
	if m != nil && m.BattleID != nil {
		return *m.BattleID
	}
	return 0
}

type UdpBattleStart struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UdpBattleStart) Reset()                    { *m = UdpBattleStart{} }
func (m *UdpBattleStart) String() string            { return proto.CompactTextString(m) }
func (*UdpBattleStart) ProtoMessage()               {}
func (*UdpBattleStart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PlayerOperation struct {
	BattleID         *int32       `protobuf:"varint,1,req,name=battleID" json:"battleID,omitempty"`
	Move             *int32       `protobuf:"varint,2,req,name=move" json:"move,omitempty"`
	OperationID      *int32       `protobuf:"varint,3,opt,name=operationID" json:"operationID,omitempty"`
	RightOperation   *RightOpType `protobuf:"varint,4,opt,name=rightOperation,enum=PBBattle.RightOpType" json:"rightOperation,omitempty"`
	OperationValue1  *int32       `protobuf:"varint,5,opt,name=operationValue1" json:"operationValue1,omitempty"`
	OperationValue2  *int32       `protobuf:"varint,6,opt,name=operationValue2" json:"operationValue2,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PlayerOperation) Reset()                    { *m = PlayerOperation{} }
func (m *PlayerOperation) String() string            { return proto.CompactTextString(m) }
func (*PlayerOperation) ProtoMessage()               {}
func (*PlayerOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerOperation) GetBattleID() int32 {
	if m != nil && m.BattleID != nil {
		return *m.BattleID
	}
	return 0
}

func (m *PlayerOperation) GetMove() int32 {
	if m != nil && m.Move != nil {
		return *m.Move
	}
	return 0
}

func (m *PlayerOperation) GetOperationID() int32 {
	if m != nil && m.OperationID != nil {
		return *m.OperationID
	}
	return 0
}

func (m *PlayerOperation) GetRightOperation() RightOpType {
	if m != nil && m.RightOperation != nil {
		return *m.RightOperation
	}
	return RightOpType_noop
}

func (m *PlayerOperation) GetOperationValue1() int32 {
	if m != nil && m.OperationValue1 != nil {
		return *m.OperationValue1
	}
	return 0
}

func (m *PlayerOperation) GetOperationValue2() int32 {
	if m != nil && m.OperationValue2 != nil {
		return *m.OperationValue2
	}
	return 0
}

type UdpUpPlayerOperations struct {
	MesID            *int32           `protobuf:"varint,1,req,name=mesID" json:"mesID,omitempty"`
	Operation        *PlayerOperation `protobuf:"bytes,2,req,name=operation" json:"operation,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *UdpUpPlayerOperations) Reset()                    { *m = UdpUpPlayerOperations{} }
func (m *UdpUpPlayerOperations) String() string            { return proto.CompactTextString(m) }
func (*UdpUpPlayerOperations) ProtoMessage()               {}
func (*UdpUpPlayerOperations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UdpUpPlayerOperations) GetMesID() int32 {
	if m != nil && m.MesID != nil {
		return *m.MesID
	}
	return 0
}

func (m *UdpUpPlayerOperations) GetOperation() *PlayerOperation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type AllPlayerOperation struct {
	Operations       []*PlayerOperation `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AllPlayerOperation) Reset()                    { *m = AllPlayerOperation{} }
func (m *AllPlayerOperation) String() string            { return proto.CompactTextString(m) }
func (*AllPlayerOperation) ProtoMessage()               {}
func (*AllPlayerOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AllPlayerOperation) GetOperations() []*PlayerOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type UdpDownFrameOperations struct {
	FrameID          *int32              `protobuf:"varint,1,req,name=frameID" json:"frameID,omitempty"`
	Operations       *AllPlayerOperation `protobuf:"bytes,2,req,name=operations" json:"operations,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UdpDownFrameOperations) Reset()                    { *m = UdpDownFrameOperations{} }
func (m *UdpDownFrameOperations) String() string            { return proto.CompactTextString(m) }
func (*UdpDownFrameOperations) ProtoMessage()               {}
func (*UdpDownFrameOperations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UdpDownFrameOperations) GetFrameID() int32 {
	if m != nil && m.FrameID != nil {
		return *m.FrameID
	}
	return 0
}

func (m *UdpDownFrameOperations) GetOperations() *AllPlayerOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type UdpUpDeltaFrames struct {
	BattleID         *int32  `protobuf:"varint,1,req,name=battleID" json:"battleID,omitempty"`
	Frames           []int32 `protobuf:"varint,2,rep,name=frames" json:"frames,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UdpUpDeltaFrames) Reset()                    { *m = UdpUpDeltaFrames{} }
func (m *UdpUpDeltaFrames) String() string            { return proto.CompactTextString(m) }
func (*UdpUpDeltaFrames) ProtoMessage()               {}
func (*UdpUpDeltaFrames) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UdpUpDeltaFrames) GetBattleID() int32 {
	if m != nil && m.BattleID != nil {
		return *m.BattleID
	}
	return 0
}

func (m *UdpUpDeltaFrames) GetFrames() []int32 {
	if m != nil {
		return m.Frames
	}
	return nil
}

type UdpDownDeltaFrames struct {
	FramesData       []*UdpDownFrameOperations `protobuf:"bytes,1,rep,name=framesData" json:"framesData,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *UdpDownDeltaFrames) Reset()                    { *m = UdpDownDeltaFrames{} }
func (m *UdpDownDeltaFrames) String() string            { return proto.CompactTextString(m) }
func (*UdpDownDeltaFrames) ProtoMessage()               {}
func (*UdpDownDeltaFrames) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UdpDownDeltaFrames) GetFramesData() []*UdpDownFrameOperations {
	if m != nil {
		return m.FramesData
	}
	return nil
}

type UdpUpGameOver struct {
	BattleID         *int32 `protobuf:"varint,1,req,name=battleID" json:"battleID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UdpUpGameOver) Reset()                    { *m = UdpUpGameOver{} }
func (m *UdpUpGameOver) String() string            { return proto.CompactTextString(m) }
func (*UdpUpGameOver) ProtoMessage()               {}
func (*UdpUpGameOver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UdpUpGameOver) GetBattleID() int32 {
	if m != nil && m.BattleID != nil {
		return *m.BattleID
	}
	return 0
}

type UdpDownGameOver struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UdpDownGameOver) Reset()                    { *m = UdpDownGameOver{} }
func (m *UdpDownGameOver) String() string            { return proto.CompactTextString(m) }
func (*UdpDownGameOver) ProtoMessage()               {}
func (*UdpDownGameOver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*BattleUserInfo)(nil), "PBBattle.BattleUserInfo")
	proto.RegisterType((*TcpEnterBattle)(nil), "PBBattle.TcpEnterBattle")
	proto.RegisterType((*UdpBattleReady)(nil), "PBBattle.UdpBattleReady")
	proto.RegisterType((*UdpBattleStart)(nil), "PBBattle.UdpBattleStart")
	proto.RegisterType((*PlayerOperation)(nil), "PBBattle.PlayerOperation")
	proto.RegisterType((*UdpUpPlayerOperations)(nil), "PBBattle.UdpUpPlayerOperations")
	proto.RegisterType((*AllPlayerOperation)(nil), "PBBattle.AllPlayerOperation")
	proto.RegisterType((*UdpDownFrameOperations)(nil), "PBBattle.UdpDownFrameOperations")
	proto.RegisterType((*UdpUpDeltaFrames)(nil), "PBBattle.UdpUpDeltaFrames")
	proto.RegisterType((*UdpDownDeltaFrames)(nil), "PBBattle.UdpDownDeltaFrames")
	proto.RegisterType((*UdpUpGameOver)(nil), "PBBattle.UdpUpGameOver")
	proto.RegisterType((*UdpDownGameOver)(nil), "PBBattle.UdpDownGameOver")
	proto.RegisterEnum("PBBattle.RightOpType", RightOpType_name, RightOpType_value)
}

func init() { proto.RegisterFile("PBBattle.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x86, 0x49, 0xdb, 0x94, 0xf2, 0x86, 0xb9, 0xc1, 0x68, 0x60, 0x24, 0x2e, 0x8a, 0xb9, 0xa9,
	0x10, 0x1b, 0xa3, 0xda, 0x3d, 0xa2, 0x94, 0x8f, 0x71, 0xc3, 0xb4, 0x35, 0xdc, 0x70, 0xe5, 0x2d,
	0x1e, 0x54, 0xa4, 0xb1, 0xe5, 0x78, 0x43, 0xfd, 0x45, 0xfc, 0x4d, 0x14, 0xe7, 0xbb, 0x9d, 0xd8,
	0x5d, 0x7d, 0x8e, 0xdf, 0xe7, 0x3c, 0xa7, 0x0e, 0xc8, 0xe9, 0x7c, 0x2e, 0xac, 0x4d, 0xe4, 0xa1,
	0x36, 0xca, 0x2a, 0x3a, 0xaa, 0xce, 0xfc, 0x1d, 0x48, 0xf1, 0x2b, 0xca, 0xa4, 0x39, 0x49, 0xaf,
	0x14, 0x0d, 0xd0, 0xbf, 0x5e, 0xc5, 0xcc, 0x9b, 0xf4, 0xa6, 0x3e, 0x0d, 0x31, 0xba, 0x70, 0xed,
	0x93, 0x05, 0xeb, 0xb9, 0x0a, 0xc1, 0xd0, 0x28, 0x77, 0xee, 0xe7, 0x67, 0xbe, 0x04, 0x59, 0x5e,
	0xea, 0x8f, 0xa9, 0x95, 0xa6, 0x00, 0xe5, 0x19, 0x23, 0xd2, 0xf8, 0x5c, 0xca, 0x8a, 0x72, 0x04,
	0x72, 0xd1, 0x19, 0xc2, 0x7a, 0x93, 0xfe, 0x34, 0x98, 0xb1, 0xc3, 0xda, 0xab, 0x2b, 0xc1, 0xdf,
	0x80, 0x44, 0xb1, 0x2e, 0x8a, 0x67, 0x52, 0xc4, 0x9b, 0x3b, 0xb4, 0x78, 0xd8, 0x0a, 0x9c, 0x5b,
	0x61, 0x2c, 0xff, 0xeb, 0x61, 0x7c, 0x9a, 0x88, 0x8d, 0x34, 0xdf, 0xb4, 0x34, 0xc2, 0xae, 0x54,
	0xda, 0xc9, 0x15, 0xa4, 0x87, 0x18, 0xac, 0xd5, 0x8d, 0x2c, 0x97, 0x7b, 0x8c, 0x40, 0x55, 0x97,
	0xdd, 0x86, 0xde, 0xd4, 0xa7, 0x07, 0x20, 0x66, 0xf5, 0xf3, 0x97, 0xad, 0x31, 0x6c, 0x30, 0xf1,
	0xa6, 0x64, 0xb6, 0xdf, 0xd8, 0x9f, 0x15, 0xfd, 0xe5, 0x46, 0x4b, 0xfa, 0x14, 0xe3, 0x9a, 0xf1,
	0x5d, 0x24, 0xd7, 0xf2, 0x2d, 0xf3, 0x1d, 0x67, 0xa7, 0x31, 0x63, 0xc3, 0xbc, 0xc1, 0x97, 0xd8,
	0x8f, 0x62, 0x1d, 0xe9, 0x2d, 0xdb, 0x8c, 0xee, 0xc1, 0x5f, 0xcb, 0xac, 0x76, 0x7d, 0x8d, 0x07,
	0x35, 0xc0, 0x09, 0x07, 0xb3, 0x67, 0x8d, 0xc3, 0x56, 0x9a, 0x7f, 0x00, 0x7d, 0x9f, 0x24, 0xdb,
	0xff, 0xc0, 0x01, 0x50, 0x33, 0x32, 0xe6, 0xb9, 0x67, 0xf8, 0x0f, 0xe4, 0x07, 0x9e, 0x44, 0xb1,
	0x5e, 0xa8, 0x3f, 0xe9, 0x27, 0x23, 0xd6, 0xb2, 0xe5, 0x36, 0xc6, 0xfd, 0xab, 0xbc, 0x54, 0xdb,
	0x1d, 0x75, 0xc8, 0x85, 0xde, 0xf3, 0x86, 0xbc, 0xeb, 0xc2, 0x8f, 0x11, 0xba, 0xbd, 0x17, 0x32,
	0xb1, 0xc2, 0xf1, 0xb3, 0x5b, 0x5e, 0x88, 0x60, 0xe8, 0x06, 0x65, 0xee, 0xa3, 0xf1, 0xf9, 0x57,
	0xd0, 0x52, 0xa9, 0x9d, 0x3b, 0x06, 0x8a, 0x5b, 0x0b, 0x61, 0x45, 0xb9, 0xd7, 0xa4, 0x99, 0x7e,
	0xfb, 0x12, 0xfc, 0x05, 0xf6, 0x9c, 0xc1, 0xe7, 0xbc, 0x7c, 0x23, 0xcd, 0xee, 0x78, 0xfe, 0x08,
	0xe3, 0x32, 0x5c, 0x5d, 0x7a, 0xf5, 0x12, 0x41, 0xfb, 0xc1, 0x47, 0x18, 0xa4, 0x4a, 0xe9, 0xf0,
	0x1e, 0x05, 0x86, 0xc2, 0x5a, 0x71, 0xf9, 0x3b, 0xf4, 0xe6, 0xbd, 0x2f, 0xfd, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x38, 0x46, 0xb6, 0x36, 0x77, 0x03, 0x00, 0x00,
}
