//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PBCommon.proto
namespace PBCommon
{
    [global::ProtoBuf.ProtoContract(Name=@"CSID")]
    public enum CSID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_LOGIN", Value=1)]
      TCP_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_REQUEST_MATCH", Value=10)]
      TCP_REQUEST_MATCH = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_CANCEL_MATCH", Value=11)]
      TCP_CANCEL_MATCH = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_BATTLE_READY", Value=51)]
      UDP_BATTLE_READY = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_PLAYER_OPERATIONS", Value=53)]
      UDP_UP_PLAYER_OPERATIONS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_DELTA_FRAMES", Value=55)]
      UDP_UP_DELTA_FRAMES = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_UP_GAME_OVER", Value=57)]
      UDP_UP_GAME_OVER = 57
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SCID")]
    public enum SCID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_LOGIN", Value=1)]
      TCP_RESPONSE_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_REQUEST_MATCH", Value=10)]
      TCP_RESPONSE_REQUEST_MATCH = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_RESPONSE_CANCEL_MATCH", Value=11)]
      TCP_RESPONSE_CANCEL_MATCH = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TCP_ENTER_BATTLE", Value=50)]
      TCP_ENTER_BATTLE = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_BATTLE_START", Value=51)]
      UDP_BATTLE_START = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_FRAME_OPERATIONS", Value=53)]
      UDP_DOWN_FRAME_OPERATIONS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_DELTA_FRAMES", Value=55)]
      UDP_DOWN_DELTA_FRAMES = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDP_DOWN_GAME_OVER", Value=57)]
      UDP_DOWN_GAME_OVER = 57
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TeamType")]
    public enum TeamType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO", Value=0)]
      NO = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM1", Value=1)]
      TEAM1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM2", Value=2)]
      TEAM2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM3", Value=3)]
      TEAM3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEAM4", Value=4)]
      TEAM4 = 4
    }
  
}